if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    include(${CMAKE_CURRENT_LIST_DIR}/compiler_options_clang.cmake)
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    include(${CMAKE_CURRENT_LIST_DIR}/compiler_options_gcc.cmake)
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
    include(${CMAKE_CURRENT_LIST_DIR}/compiler_options_intel.cmake)
elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    include(${CMAKE_CURRENT_LIST_DIR}/compiler_options_msvc.cmake)
endif()
