# using Visual Studio C++
string(REGEX REPLACE "/W[0-4]" "/W4" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
add_compile_options(/W4)
#add_compile_options(/MP${BUILD_JOBS})
add_compile_options(/utf-8)
add_compile_options(/external:anglebrackets)
add_compile_options(/external:W0)
add_compile_options(/external:templates-)
#add_compile_options(/Gv)
add_compile_options("$<$<CONFIG:Release>:/Oi>")
add_compile_options("$<$<CONFIG:Release>:/Gy>")
#add_compile_options("$<$<CONFIG:Release>:/GL>")
add_compile_options("$<$<CONFIG:Release>:/Gw>")
#add_compile_options("$<$<CONFIG:Release>:/Ob3>")
add_compile_options(/Zi)
add_compile_options(/permissive-)
add_compile_options(/sdl)
add_compile_options(/Y-)
add_compile_options(/bigobj)
add_compile_options(/cgthreads8)
add_compile_options(/EHsc)
add_compile_options(${DEFAULT_CXX_DEBUG_INFORMATION_FORMAT})
add_compile_options(${DEFAULT_CXX_EXCEPTION_HANDLING})
#add_compile_options(/arch:AVX2)
#add_compile_options("$<$<CONFIG:Release>:/MD>")
#add_compile_options("$<$<CONFIG:Debug>:/MDd>")
#add_compile_options("$<$<CONFIG:Release>:/MT>")
#add_compile_options("$<$<CONFIG:Debug>:/MTd>")

add_link_options("$<$<CONFIG:Debug>:/INCREMENTAL>")
#add_link_options("$<$<CONFIG:Release>:/LTCG>")
add_link_options("$<$<CONFIG:Release>:/DEBUG>")
add_link_options("$<$<CONFIG:Release>:/OPT:REF>")
add_link_options("$<$<CONFIG:Release>:/OPT:ICF>")
add_link_options("$<$<CONFIG:Release>:/INCREMENTAL:NO>")
